module.exports = {
  content: ["./App.tsx", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#59021a",
          light: "#ffb2b9",
          dark: "#781c2e",
          container: "#781c2e",
          fixed: "#ffdadc",
          fixedDim: "#ffb2b9",
        },
        onPrimary: "#ffffff",
        secondary: {
          DEFAULT: "#4e5f7c",
          container: "#c9dbfd",
        },
        tertiary: {
          DEFAULT: "#372700",
          fixed: "#ffdf9e",
          fixedDim: "#eac16a",
          container: "#523c00",
        },
        primaryLight: "#ffb2b9",
        primaryDark: "#781c2e",
        surface: "#fcf9f8",
        surfaceContainerLowest: "#ffffff",
        surfaceContainerLow: "#f6f3f2",
        surfaceContainer: "#f0edec",
        surfaceContainerHigh: "#ebe7e7",
        surfaceContainerHighest: "#e5e2e1",
        onSurface: "#1c1b1b",
        onSurfaceVariant: "#564243",
        textPrimary: "#1c1b1b",
        textSecondary: "#564243",
        textTertiary: "#897173",
        border: "#dcc0c1",
        outline: "#897173",
        outlineVariant: "#dcc0c1",
        error: {
          DEFAULT: "#ba1a1a",
          container: "#ffdad6",
        },
        success: "#22C55E",
        warning: "#F59E0B",
        highlight: {
          yellow: "#FEF3C7",
          green: "#D1FAE5",
          blue: "#DBEAFE",
          pink: "#FCE7F3",
        },
      },
      fontFamily: {
        headline: ["PlayfairDisplay_700Bold"],
        "headline-regular": ["PlayfairDisplay_400Regular"],
        "headline-italic": ["PlayfairDisplay_400Regular_Italic"],
        sans: ["Inter_400Regular"],
        "sans-medium": ["Inter_500Medium"],
        "sans-semibold": ["Inter_600SemiBold"],
        "sans-bold": ["Inter_700Bold"],
      },
    },
  },
  plugins: [],
};
